version: '3.8'
volumes:
  prometheus_data: {}
services:
  service1:
    build:
      context: .
      target: service1
      dockerfile: Dockerfile
    ports:
      - 3000:3005
  service2:
    build:
      context: .
      target: service2
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  service3:
    build:
      context: .
      target: service3
      dockerfile: Dockerfile
    ports:
      - 3002:3002
      - 9464:9464
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - 9999:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
